-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.items
(
    itemid serial NOT NULL,
    vaultid integer NOT NULL,
    itemname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    username character varying(255) COLLATE pg_catalog."default",
    encryptedpassword bytea NOT NULL,
    url character varying(255) COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updatedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT items_pkey PRIMARY KEY (itemid)
);

CREATE TABLE IF NOT EXISTS public.users
(
    userid serial NOT NULL,
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    masterpasswordhash bytea NOT NULL,
    masterpasswordsalt bytea NOT NULL,
    createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updatedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (userid),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.vaults
(
    vaultid serial NOT NULL,
    userid integer NOT NULL,
    vaultname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updatedat timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT vaults_pkey PRIMARY KEY (vaultid)
);

ALTER TABLE IF EXISTS public.items
    ADD CONSTRAINT items_vaultid_fkey FOREIGN KEY (vaultid)
    REFERENCES public.vaults (vaultid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vaults
    ADD CONSTRAINT vaults_userid_fkey FOREIGN KEY (userid)
    REFERENCES public.users (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;